name: Create Daily Release Candidate Branch and Open PR

on:
  workflow_dispatch:  # Allows you to manually trigger the action from the GitHub UI
  schedule:
    - cron: '0 22 * * *'   # Runs every day at 3 PM Pacific Time during Daylight Saving Time (UTC-7)

env:
    PROJECT_NAME: "NAME"

jobs:
  create_branch_and_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: main  # Checkout the release branch
          fetch-depth: 0  # Fetch all history for all branches

      # Fetch all branches without specifying the local branch
      - name: Fetch the latest main branch
        run: |
          git fetch origin

      - name: Get the current date and hour
        id: datetime
        run: echo "datetime=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build new RC Branch name
        id: branch_name
        run: echo "branch_name="rc/${{ env.datetime }}"" >> $GITHUB_ENV

      - name: Reset release branch
        run: |
          git fetch origin release:release
          git reset --hard release

      - name: Create a new branch and Push
        run: |
          git rev-parse --abbrev-ref HEAD
          git checkout -b "${{ env.branch_name }}"
          git push origin "${{ env.branch_name }}"
          echo "Branch ${{ env.branch_name }} created and pushed to origin."

      - name: Merge main -> ${{ env.branch_name }}
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: ${{ env.branch_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            title: "release(${{ env.PROJECT_NAME }}): ${{ env.datetime }}"
            body: |
              - RC ${{ env.datetime }}

              Auto-generated by [create-pull-request][1]

              [1]: https://github.com/peter-evans/create-pull-request
            branch: "${{ env.branch_name }}"