name: Create Daily Release Candidate Branch and Open PR

on:
  workflow_dispatch:  # Allows you to manually trigger the action from the GitHub UI
  schedule:
    - cron: '0 22 * * *'   # Runs every day at 3 PM Pacific Time during Daylight Saving Time (UTC-7)

jobs:
  create_branch_and_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main  # Checkout the main branch
          fetch-depth: 0  # Fetch all history for all branches

      - name: Extract and print just the repository name
        id: repo_name
        run: |
          echo "repo_name=$(echo "${{ github.repository }}" | cut -d'/' -f2)" >> $GITHUB_ENV
          echo "Repository Name: $REPO_NAME"

      - name: Fetch the latest main branch
        run: |
          git fetch origin

      - name: Get the current date and hour
        id: datetime
        run: echo "datetime=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build new RC Branch name
        id: branch_name
        run: echo "branch_name="rc/${{ env.datetime }}"" >> $GITHUB_ENV

      - name: Check if branch already exists
        id: check_branch
        run: |
          if git ls-remote --heads origin ${{ env.branch_name }} | grep -q ${{ env.branch_name }}; then
            echo "Branch ${{ env.branch_name }} already exists."
            echo "exists=true" >> $GITHUB_ENV
            exit 0
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Reset release branch
        if: env.exists == 'false'
        run: |
          git fetch origin release:release
          git reset --hard release

      # This will Create the new branch rc/YYYY-MM-DD using the `release` branch using release as HEAD
      - name: Create Pull Request
        if: env.exists == 'false'
        uses: peter-evans/create-pull-request@v6
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            title: "release(${{ env.repo_name }}): ${{ env.datetime }}"
            body: |
              - RC ${{ env.datetime }}

              Auto-generated by [create-pull-request][1]

              [1]: https://github.com/peter-evans/create-pull-request
            branch: "${{ env.branch_name }}"

      # Merge latest code into the RC in order to avoid differences
      - name: Merge main -> ${{ env.branch_name }}
        if: env.exists == 'false'
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          message: Merge main into ${{ env.branch_name }}
          target_branch: ${{ env.branch_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
